source:
  label: KEGG Compound
  type: Chemical compound
  name: kegg.compound
  prefix: http://identifiers.org/drugbank

target:
  label: KEGG Compound
  type: Chemical compound
  name: kegg.compound
  prefix: http://bio2rdf.org/kegg.compound

link:
  label: Further information about the subject resource
  namespace: linkdb
  prefix: https://www.genome.jp/linkdb/
  predicate: equivalent
  file: pairs.tsv

reverse_link:
  label: Further information about the subject resource
  namespace: linkdb
  prefix: https://www.genome.jp/linkdb/
  predicate: equivalent

update:
  frequency: Quarterly
  method:  python3 make_pairs.py
